### ISSUE TITLE
Accreditation

### ISSUE THREAD

**Issue by shuishida** [Farama-Foundation/Miniworld#101]
Hello. It is great to see the work going into the Gymnasium project. As a former MiniWorld user, it is very exciting to see that MiniWorld is now officially supported as a part of the Gymnasium project going forward.

I was just wondering why there isn't a proper accreditation for @maximecb, who I believe is the original developer of MiniWorld, in the README / the [documentation](https://miniworld.farama.org/). Apart from the bibtex citation for gym_miniworld in the README (which points to a repo which no longer exists), I couldn't find any description about the fact that Miniworld 2.0 is based on MiniWorld by @maximecb. 

I am sure there has been a proper conversation and agreement about this, but I think it would be nice to have a proper accreditation nevertheless. When I first discovered MiniWorld, I found it very empowering to know that it was created by a single developer, and it would be a pity not to honour that history.

**Comment by pseudo-rnd-thoughts** [comment]
Hey, yes we will look to update that and properly credit maximecb for her work. 

> @misc{gym_miniworld,
  author = {Chevalier-Boisvert, Maxime},
  title = {MiniWorld: Minimalistic 3D Environment for RL & Robotics Research},
  year = {2018},
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/maximecb/gym-miniworld}},
}

I should note that the bibtex citation suggestion does just have maxime as the author of the project
