### ISSUE TITLE
Add collision function

### ISSUE THREAD

**Issue by Zachary19980701** [Farama-Foundation/MiniWorld#67]
Thanks for your contribution.
In my project I need to implement collision effect. I now do this by comparing the coordinates of the anchor with the coordinates of the wall. I would like to ask if there is a better way to do it, maybe I can make a contribution to this library.

**Comment by Zachary19980701** [comment]
I add collision function in miniworld.py file to achieve this function
```python
    def collision(self, ent0, min_x, max_x, min_z, max_z):
        if ent0.pos[0]>min_x and ent0.pos[0]<max_x and ent0.pos[2]>min_y and ent0.pos[2]<max_y:
            return True
        else:
            return False
```

**Comment by pseudo-rnd-thoughts** [comment]
Would you be able to make a PR to add this feature?

**Comment by Zachary19980701** [comment]
I will add this feature in future work
