### ISSUE TITLE
[Bug Report] Getting error: gym.error.NameNotFound: Environment doesn't exist. 

### ISSUE THREAD

**Issue by freyavs** [Farama-Foundation/Miniworld#80]
Hi, I'm not sure if this is a bug or if I'm doing something wrong, but I'm trying to use this project with the gym interface. I'm getting the following error

 `gym.error.NameNotFound: Environment MiniWorld-CollectHealth doesn't exist. `

**Code example**
```
import gym
import gym_miniworld

env = gym.make("MiniWorld-CollectHealth-v0")
```

**System Info**
 * miniworld installed from source
 * Running Manjaro (Linux)
 * Python v3.10.8

**Additional context**
I did some logging, the environments get registered and are in the registry immediately afterwards. But then later, when calling `gym.make`,  they are not in the registry anymore:
![2022-12-07_17-32](https://user-images.githubusercontent.com/56410697/206236235-80e59b3f-7d9f-4827-bb8d-b9ed1aeee6b4.png)

I've tried the exact same workflow on a similar project, where it does work. So, not sure if this is a bug or what else to do here?

**Comment by pseudo-rnd-thoughts** [comment]
Could you try
```python
import gym
import gym_miniworld

print(gym.envs.registry.keys())
env = gym.make("MiniWorld-CollectHealth-v0")
```
On a fresh install, gym contains the environment for me but raises an error related to pyglet instead of `NameNotFound`

**Comment by freyavs** [comment]
With installing via pip, I run into another problem. For running on a cluster, setting the PYOPENGL_PLATFORM environment does not seem to be working? (the alternative solution mentioned is not relevant for me)

`PYOPENGL_PLATFORM=egl python3 your_script.py`

I also tried this locally, and get the same error (in pyglet)

`ValueError: Unknown OpenGL API: None`

**Comment by pseudo-rnd-thoughts** [comment]
@BolunDai0216 Would you be able to help with this?

**Comment by freyavs** [comment]
That solved most of the problems, thank you! I'm still seeing the `ValueError: Unknown OpenGL API: None` on my cluster, but I assume for pyglet to work the underlying OpenGL drivers etc. should be set up?

**Comment by BolunDai0216** [comment]
Yes, I think OpenGL should be setup.
